services:
  my_website:
    image: dominikmatic/my_website:latest
    container_name: my_website
    restart: 'unless-stopped'
    networks:
      - internal
  nginx:
    image: nginx:1.29.0-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /opt/my_website/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
    restart: 'unless-stopped'
    networks:
      - internal

networks:
  internal:
    driver: bridge
