- name: install cronie
  package:
    name: cronie
    state: present

- name: ensure crond is running
  service:
    name: crond
    state: started
    enabled: yes

- import_tasks: docker.yml
- import_tasks: certbot.yml
