- name: install docker
  tags: docker
  package:
    name:
      - docker
    state: latest

- name: start and enable docker service
  tags: docker
  service:
    name: "docker"
    state: started
    enabled: yes

- name: create a letsencrypt directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/letsencrypt/
    state: directory
    mode: '0755'

- name: copy lentsencrypt files from host to remote
  ansible.builtin.copy:
    src: /etc/letsencrypt/
    dest: /etc/letsencrypt/
    owner: root
    group: root
    mode: '0644'

