---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon"

- hosts: web_servers
  become: true
  roles:
    - web_servers