---

- hosts: web_servers
  become: true

  vars:
    deploy_path: /opt/my_website
    nginx_conf_dir: "{{ deploy_path }}/nginx"

  tasks:
  - name: ensure deploy directory exists
    file:
      path: "{{ deploy_path }}"
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: ensure nginx config directory exists
    file:
      path: "{{ nginx_conf_dir }}"
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: copy docker-compose.yml to deploy directory
    copy:
      src: files/deploy/docker-compose.yml
      dest: "{{ deploy_path }}/docker-compose.yml"
      owner: root
      group: root
      mode: '0644'

  - name: copy nginx.conf to nginx config directory
    copy:
      src: files/deploy/nginx.conf
      dest: "{{ nginx_conf_dir }}/nginx.conf"
      owner: root
      group: root
      mode: '0644'

  - name: run docker compose up -d
    community.docker.docker_compose_v2:
      project_src: "{{ deploy_path }}"
      state: present
      recreate: always
      pull: always
