---

- hosts: web_servers
  become: true
  tasks:

  - name: pull a docker image
    tags: docker
    docker_image:
      name: dominikmatic/my_website:latest
      source: pull
      force_source: true

  - name: (re)start the container
    community.docker.docker_container:
      name: my_website
      image: dominikmatic/my_website:latest
      state: started
      restart: yes
      ports:
       - "80:3080"
       - "443:3443"
      volumes:
        - "/etc/letsencrypt/:/etc/letsencrypt/"
